baseURL = 'https://mtarnawa.org/'
languageCode = 'en-us'
title = 'Mateusz Tarnawa'
theme = "black-and-light"

author = "Mateusz Tarnawa"
canonifyurls = true

pygmentsUseClassic            = true
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses            = true

[markup.goldmark.renderer]
   unsafe = true

[services]
  [services.disqus]
    shortname = 'mtarnawa'

[params]
  sitename = "Mateusz Tarnawa"
  disableWebFonts = false
  dateFormat = "2 January 2006"

[[menu.main]]
    name = "Blog"
    url  = "/"
[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Flickr"
    url  = "https://www.flickr.com/photos/204114481@N08/"
[[menu.main]]
    name = "Linkedin"
    url  = "https://www.linkedin.com/in/mtarnawa/"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/mtarnawa"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
